### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by kakoybaldezh** [AveYo/ShowMMR#10]
I did everything according to the instructions, but still nothing works, i cant see mmr in the list of recent matches

**Comment by AveYo** [comment]
issue #8, it might be broken for czech, finnish, french, greek, tchinese, thai, turkish, ukrainian, vietnamese and japanese, but ok for the other languages.

will fix next

**Comment by kakoybaldezh** [comment]
I'm Russian

**Comment by kakoybaldezh** [comment]
And UI top bar doesnt work too

**Comment by kakoybaldezh** [comment]
Well, i fix that. But UI top bar still not working  -_-

**Comment by AveYo** [comment]
the top bar script haven't worked in a while, valve has removed mmr values from dota_game_account_client_debug command

**Comment by AveYo** [comment]
but I guess I could add it as a feature in showmmr mod?

**Comment by AveYo** [comment]
main issue should be fixed with 1.5
