### ISSUE TITLE
is it avalable for linux?

### ISSUE THREAD

**Issue by s10wn** [AveYo/ShowMMR#14]
Can I add your scripts, when I have OC linux(Arch)?

**Comment by AveYo** [comment]
the mod is available pre-compiled in the release folder  
but to compile it yourself from source you need Dota Workshop Tools and that's not trivial to get working under linux


the tool can be compiled under linux, someone already did it on arch, see #2  
will add a linux shell script at some point

**Comment by s10wn** [comment]
thx
