### ISSUE TITLE
how to install a new version?

### ISSUE THREAD

**Issue by SQWIZI1337** [AveYo/ShowMMR#21]
how to install a new version?

**Comment by AveYo** [comment]
of what?

**Comment by SQWIZI1337** [comment]
ShowMMR

**Comment by AveYo** [comment]
You build it and the script does it for you or you follow the readme for manual installation

release/ folder has couple variants of the mod, pick one i.e. default_background/
inside is the game folder that you must copy-paste over your dota 2 beta/game/ folder, see readme:

> To install the mod:
>  - open Steam > Library > Dota2 > right-click Properties > Installed files > Browse..
>  - copy release/game/ subfolder over there, overwriting existing files:
>  game/dota_mods/pak01_dir.vpk
>  game/dota/gameinfo_branchspecific.gi
>  - or skip gameinfo_branchspecific.gi and use instead launch option: -language mods
>
>  To remake the mod from source:
>  - need Dota2 Workshop Tools DLC for resourcecompile xml source files
>  - run dota_mod_builder.bat, auto-compiled vpkmod will create the release vpk archive
>
>  To explore release/game/dota_mods/pak01_dir.vpk and compiled *_c content:
>  - use VRF tool by SteamDatabase: github.com/SteamDatabase/ValveResourceFormat/
