### ISSUE TITLE
 ̵W̵h̵y̵ ̵d̵i̵d̵ ̵y̵o̵u̵ ̵r̵e̵m̵o̵v̵e̵ ̵S̵h̵o̵w̵M̵M̵R̵?̵ ̵I̵s̵ ̵i̵t̵ ̵n̵o̵t̵ ̵s̵a̵f̵e̵?̵ ̵

### ISSUE THREAD

**Issue by simon-stentoft** [AveYo/ShowMMR#3]
Is it not safe to use? Why did you remove it

**Comment by AveYo** [comment]
Where did you get that wrong idea from?
It was not removed. The release was refreshed, in v1.3 it's working just fine.

**Comment by AveYo** [comment]
And the initial announcement is still there on reddit   
https://old.reddit.com/r/DotA2/comments/14byy92/showmmr_a_dashboard_mod_to_bring_back_the_mmr/
https://twitter.com/redditdota2/status/1670251019060609025?cxt=HHwWgoC8zfqc9q0uAAAA
but 2 days have already passes, it naturally fall couple pages back

**Comment by AveYo** [comment]
So, in the releases tab, I keep only the latest one to not cause unnecessary confusion.
But you can access all the previous ones if you switch to tags (https://github.com/AveYo/ShowMMR/tags)
Code is the same as in the repository history anyway, there are no separate binaries provided.

So if anyone wants to link to a specific release, can use one of the past tags
for example: https://github.com/AveYo/ShowMMR/releases/tag/2023.06.19
But for the latest it's always https://github.com/AveYo/ShowMMR/releases/latest
